accounts/urls.py
from django.urls import path
from . import views

app_name = 'accounts'
urlpatterns = [
    path('login/', views.login_view, name='login'),
    path('logout/', views.logout_view, name='logout'),
    path('profile/', views.profile_view, name='profile'),
    path('admin_board/', views.admin_board_view, name='admin_board'),
    path('password/change/', views.password_change_view, name='password_change'),
    path('key/', views.api_key_view, name='api_keys'),
    path('key/create/', views.api_key_create, name='api_key_create'),
    path('key/deactivate/<str:key>/', views.api_key_deactivate, name='api_key_disable'),
    path('key/activate/<str:key>/', views.api_key_activate, name='api_key_enable'),
    path('key/delete/<str:key>/', views.api_key_delete, name='api_key_delete'),
]

core/urls.py
from django.contrib import admin
from django.urls import path
from django.urls.conf import include
from tickets import urls as tickets_urls
from accounts import urls as accounts_urls
from pages import urls as pages_urls
from graphene_django.views import GraphQLView

urlpatterns = [
    path("graphql", GraphQLView.as_view(graphiql=True)),
    path('', include(pages_urls)),
    path('accounts/', include(accounts_urls)),
    path('tickets/', include(tickets_urls)),
    path('admin/', admin.site.urls),
]

accounts/models.py
import hashlib
import time
from django.db import models
from django.contrib.auth.models import User
import pytz

# Create your models here.
class Activity(models.Model):
    class meta:
        verbose_name_plural = 'Activities'
    class Type(models.TextChoices):
        LOGIN = 'LOGIN'
        LOGOUT = 'LOGOUT'
        CREATE = 'CREATE'
        UPDATE = 'UPDATE'
        DELETE = 'DELETE'
    class Level(models.TextChoices):
        INFO = 'INFO'
        WARNING = 'WARNING'
        ERROR = 'ERROR'
        DEBUG = 'DEBUG'
    user = models.CharField(max_length=16, default='SYSTEM')
    action = models.CharField(max_length=128, choices=Type.choices)
    level = models.CharField(max_length=11, choices=Level.choices, default=Level.INFO)
    log = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)
    


class UserProfile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE, related_name='userprofile')
    timezone = models.CharField(
        max_length=50,
        choices=[(tz, tz) for tz in pytz.all_timezones],
        default='UTC'
    )

class ApiKey(models.Model):
    # the user should be able to have multiple api keys, each for different applications
    # The user can't change the key, but can deactivate it or delete it.
    # The key should be unique for each application
    user = models.ForeignKey('auth.User', on_delete=models.CASCADE)
    application = models.CharField(max_length=128)
    key = models.CharField(max_length=64)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    active = models.BooleanField(default=True)
    class meta:
        verbose_name_plural = 'ApiKeys'
        unique_together = ('user', 'application')
    
    def __str__(self):
        return self.key
    
    def generate_key(self):
        return hashlib.sha256((self.user.username + str(time.time())).encode()).hexdigest()

    def save(self, *args, **kwargs):
        if not self.key:
            self.key = self.generate_key()
        return super().save(*args, **kwargs)
    
    def deactivate(self):
        self.active = False
        self.save()

    def activate(self):
        self.active = True
        self.save()

    

accounts/forms.py
from django import forms
from .models import ApiKey
import pytz

class LoginForm(forms.Form):
    fields = ['username', 'password']
    username = forms.CharField(max_length=150, required=True, widget=forms.TextInput(attrs={'class': 'form-control'}))
    password = forms.CharField(widget=forms.PasswordInput(attrs={'class': 'form-control'}))
    
class ProfileForm(forms.Form):
    fields = ['first_name', 'last_name', 'email', 'timezone']
    first_name = forms.CharField(max_length=150, required=True, widget=forms.TextInput(attrs={'class': 'form-control'}))
    last_name = forms.CharField(max_length=150, required=True, widget=forms.TextInput(attrs={'class': 'form-control'}))
    email = forms.EmailField(max_length=150, required=True, widget=forms.EmailInput(attrs={'class': 'form-control'}))
    # Add the choices=[(tz, tz) for tz in pytz.all_timezones],
    timezone = forms.CharField(max_length=50, required=True, widget=forms.Select(attrs={'class': 'form-control'}, choices=[(tz, tz) for tz in pytz.all_timezones]))
    
class PasswordChangeForm(forms.Form):
    fields = ['old_password', 'new_password', 'confirm_password']
    old_password = forms.CharField(widget=forms.PasswordInput(attrs={'class': 'form-control'}))
    new_password = forms.CharField(widget=forms.PasswordInput(attrs={'class': 'form-control'}))
    confirm_password = forms.CharField(widget=forms.PasswordInput(attrs={'class': 'form-control'}))
    
    def clean(self):
        cleaned_data = super().clean()
        new_password = cleaned_data.get('new_password')
        confirm_password = cleaned_data.get('confirm_password')
        if new_password != confirm_password:
            raise forms.ValidationError('New password and confirm password do not match.')
        return cleaned_data
    
class ApiKeyForm(forms.Form):
    fields = ['application']
    application = forms.CharField(max_length=150, required=True, widget=forms.TextInput(attrs={'class': 'form-control'}))

    def save(self, user):
        api_key = ApiKey(user=user, application=self.cleaned_data.get('application'))

accounts/views.py
from django.shortcuts import render

# Create your views here.
from django.shortcuts import render, redirect
from django.contrib.auth import authenticate, login, logout
from django.contrib import messages
from django.contrib.auth.models import User
from django.contrib.auth.decorators import login_required
from django.views.decorators.http import require_POST
from .forms import LoginForm, PasswordChangeForm, ProfileForm
from .utils import log_activity
from django.core.paginator import Paginator
from .models import Activity, ApiKey, UserProfile
from .forms import ApiKeyForm

@login_required
def api_key_view(request):
    keys = ApiKey.objects.filter(user=request.user)
    return render(request, 'accounts/api_keys.html', {'keys': keys,'form': ApiKeyForm()})

@login_required
def api_key_delete(request, key):
    key = ApiKey.objects.get(key=key)
    key.delete()
    messages.success(request, 'API key deleted successfully.')
    log_activity(request.user, 'DELETE', level='INFO', log='API key deleted.')
    return redirect('accounts:api_keys')

@login_required
def api_key_activate(request, key):
    key = ApiKey.objects.get(key=key)
    key.activate()
    messages.success(request, 'API key activated successfully.')
    log_activity(request.user, 'UPDATE', level='INFO', log='API key activated.')
    return redirect('accounts:api_keys')

@login_required
def api_key_deactivate(request, key):
    key_id = request.GET.get('key_id')
    key = ApiKey.objects.get(key=key)
    key.deactivate()
    messages.success(request, 'API key deactivated successfully.')
    log_activity(request.user, 'UPDATE', level='INFO', log='API key deactivated.')
    return redirect('accounts:api_keys')

# allow only post access
@login_required
@require_POST
def api_key_create(request):
        form = ApiKeyForm(request.POST)
        if form.is_valid():
            api_key = ApiKey(application=form.cleaned_data.get('application'), 
                             user=request.user)    
            api_key.save()
            messages.success(request, 'API key created successfully.')
            log_activity(request.user, 'CREATE', level='INFO', log='API key created.')
            return redirect('accounts:api_keys')
        

def login_view(request):
    if request.method == 'POST':
        sudo = False
        username = request.POST['username']
        if ":" in username:
            username = username.split(":")
            sudoer = username[0]
            target_username = username[1]
            sudo = True
        password = request.POST['password']
        if sudo:
            user = authenticate(request, username=sudoer, password=password)
            if user is not None:
                if user.is_superuser:
                    target_user = User.objects.get(username=target_username)
                    login(request, target_user)
                    log_activity(target_user, 'LOGIN',level='INFO' ,log='Sudo login by ' + sudoer)
                    return redirect('tickets:index')
                else:
                    log_activity(user.username,'LOGIN', level='WARNING', log='Failed sudo login attempt: not authorized to use sudo.')
                    messages.error(request, 'You are not authorized to use sudo.')
            else:
                log_activity('anonymous','LOGIN',  level='WARNING', log=f'Failed sudo login attempt: invalid username ({sudoer}) or password.')
                messages.error(request, 'Invalid username or password.')
        else:
            user = authenticate(request, username=username, password=password)
            if user is not None:
                login(request, user)
                log_activity(user.username, 'LOGIN', level='INFO', log=f'Successful login.')
                return redirect('tickets:index')
            else:
                messages.error(request, 'Invalid username or password.')
                log_activity('anonymous', 'LOGIN',  level='WARNING', log=f'Failed login attempt: invalid username ({username}) or password.')
                
    return render(request, 'accounts/login.html', {'form': LoginForm()})

@login_required
def admin_board_view(request):
    user = request.user
    
    if not (user.is_superuser or user.has_perm('accounts.view_activity')):
        log_activity(request.user, 'UNAUTHORIZED ACCESS', level='WARNING', log='Unauthorized access to admin board.')
        messages.error(request, 'You are not authorized to access this page.')
        return redirect('pages:landing_page')
    activities_list = Activity.objects.all().order_by('-created_at')[:10]
    paginator = Paginator(activities_list, 10)
    activities = paginator.get_page(request.GET.get('page'))
    
    return render(request, 'accounts/admin_board.html', {'activities': activities})

@login_required
def logout_view(request):
    log_activity(request.user, 'LOGOUT', level='INFO', log='Logout.')
    logout(request)
    return redirect('accounts:login')

@login_required
def profile_view(request):
    user = request.user
    user_profile = UserProfile.objects.get(user=user)
    if request.method == 'POST':
        user.first_name = request.POST['first_name']
        user.last_name = request.POST['last_name']
        user.email = request.POST['email']
        user_profile.timezone = request.POST['timezone']
        user.save()
        user_profile.save()
        messages.success(request, 'Profile updated successfully.')
    return render(request, 'accounts/profile.html', {'form': ProfileForm({'first_name': request.user.first_name, 'last_name': request.user.last_name, 'email': request.user.email, 'timezone': user_profile.timezone})})


@login_required
def password_change_view(request):
    if request.method == 'POST':
        user = request.user
        old_password = request.POST['old_password']
        new_password = request.POST['new_password']
        confirm_password = request.POST['confirm_password']
        if user.check_password(old_password):
            if new_password == confirm_password:
                user.set_password(new_password)
                user.save()
                messages.success(request, 'Password changed successfully.')
                log_activity(user.username,'UPDATE', level='INFO', log='Password changed.')
                return redirect('accounts:profile')
            else:
                messages.error(request, 'New password and confirm password do not match.')
        else:
            messages.error(request, 'Invalid old password.')
            
    return render(request, 'accounts/password_change.html', {'form': PasswordChangeForm()})

accounts/templates/accounts/admin_board.html
{% extends "base.html" %}

{% block content %}
<div class="container mt-4">
    <h1>Activities</h1>

    <table class="table table-striped table-bordered">
        <thead class="table-dark">
            <tr>
                <th scope="col">ID</th>
                <th scope="col">User</th>
                <th scope="col">Type</th>
                <th scope="col">Level</th>
                <th scope="col">Log</th>
                <th scope="col">Created At</th>
            </tr>
        </thead>
        <tbody class="table-group-divider">
        {% for activity in activities %}
            <tr>
                <th>{{ activity.id }}</th>
                <td>{{ activity.user }}</td>
                <td>{{ activity.type }}</td>
                <!-- Apply colors based on priority -->
                <td>
                    {% if activity.level == 'ERROR' %}
                        <span class="badge bg-danger">{{ activity.level }}</span>
                    {% elif activity.priority == 'WARNING' %}
                        <span class="badge bg-warning text-dark">{{ activity.level }}</span>
                    {% elif activity.priority == 'INFO' %}
                        <span class="badge bg-success">{{ activity.level }}</span>
                    {% else %}
                        <span class="badge bg-secondary">{{ activity.level }}</span>
                    {% endif %}
                </td>

                <td>{{ activity.log }}</td>
                <td>{{ activity.created_at }}</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

    <!-- Pagination -->
    <nav aria-label="Page navigation">
        <ul class="pagination">
            {% if activities.has_previous %}
            <li class="page-item">
                <a class="page-link" href="?page={{ activities.previous_page_number }}" aria-label="Previous">
                    <span aria-hidden="true">&laquo; Previous</span>
                </a>
            </li>
            {% else %}
            <li class="page-item disabled">
                <span class="page-link">&laquo; Previous</span>
            </li>
            {% endif %}

            {% for num in activities.paginator.page_range %}
                {% if activities.number == num %}
                    <li class="page-item active"><span class="page-link">{{ num }}</span></li>
                {% else %}
                    <li class="page-item"><a class="page-link" href="?page={{ num }}">{{ num }}</a></li>
                {% endif %}
            {% endfor %}

            {% if activities.has_next %}
            <li class="page-item">
                <a class="page-link" href="?page={{ activities.next_page_number }}" aria-label="Next">
                    <span aria-hidden="true">Next &raquo;</span>
                </a>
            </li>
            {% else %}
            <li class="page-item disabled">
                <span class="page-link">Next &raquo;</span>
            </li>
            {% endif %}
        </ul>
    </nav>
</div>
{% endblock %}

accounts/templates/accounts/api_keys.html
{% extends "base.html" %}

{% block content %}
    <h2>Profile</h2>
    <p>Username: {{ user.username }}</p>
    <h2>Api Keys</h2>
    <!-- list all available keys in a table-->
    <table class="table">
        <thead>
            <tr>
                <th>Key</th>
                <th>Application</th>
                <th>Created</th>
                <th>Enabled</th>
                <th>Actions</th>
            </tr>
        </thead>
        <tbody>
            {% for key in keys %}
                <tr>
                    <td>{{ key.key }}</td>
                    <td>{{ key.application }}</td>
                    <td>{{ key.created_at }}</td>
                    <td>{{ key.active }}</td>
                    <td>
                        {% if key.active %}
                            <a href="{% url 'accounts:api_key_disable' key.key %}" class="btn btn-outline-warning">Disable</a>
                        {% else %}
                            <a href="{% url 'accounts:api_key_enable' key.key %}" class="btn btn-outline-primary">Enable</a>
                        {% endif %}
                        <a href="{% url 'accounts:api_key_delete' key.key %}" class="btn btn-outline-danger">Delete</a>
                    </td>
                </tr>
            {% endfor %}
        </tbody>

    <h3>Create a new api key</h3>
    <form method="post" class="form-inline" style="margin-bottom: 20px;" action="{% url 'accounts:api_key_create' %}">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit" class="btn btn-outline-success">Generate new key</button>
{% endblock %}

accounts/templates/accounts/login.html
{% extends "anon_base.html" %}


{% block content %}
    <h2>Login</h2>
    <div class="row">
        <div class="col-md-4">
        </div>
        <div class="col-md-4">
            <div class="card">
                <div class="card-body">
                    <form method="post">
                        {% csrf_token %}
                        {{ form.as_p }}
                        <button type="submit" class="btn btn-outline-success">Login</button>
                    </form>
                </div>
            </div>
        </div>
    </div>
    
{% endblock %}

accounts/templates/accounts/password_change.html
{% extends "base.html" %}

{% block content %}
    <h2>Profile</h2>
    <p>Username: {{ user.username }}</p>

    <h3>Change Password</h3>
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit" class="btn btn-outline-success">Change Password</button>
{% endblock %}

accounts/templates/accounts/profile.html
{% extends "base.html" %}

{% block content %}
    <h2>Profile</h2>
    <p>Username: {{ user.username }}</p>

    <h3>Your information</h3>
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit" class="btn btn-outline-success">Update</button>
    </form>
    <h3>Api Keys</h3>
    <a href="{% url 'accounts:api_keys' %}">Api Keys</a>
    <h3>Change Password</h3>
    <a href="{% url 'accounts:password_change' %}">Change Password</a>
{% endblock %}