accounts/urls.py
from django.urls import path
from . import views

app_name = 'accounts'
urlpatterns = [
    path('login/', views.login_view, name='login'),
    path('logout/', views.logout_view, name='logout'),
    path('profile/', views.profile_view, name='profile'),
    path('admin_board/', views.admin_board_view, name='admin_board'),
    path('password/change/', views.password_change_view, name='password_change'),
    path('key/', views.api_key_view, name='api_keys'),
    path('key/create/', views.api_key_create, name='api_key_create'),
    path('key/deactivate/<str:key>/', views.api_key_deactivate, name='api_key_disable'),
    path('key/activate/<str:key>/', views.api_key_activate, name='api_key_enable'),
    path('key/delete/<str:key>/', views.api_key_delete, name='api_key_delete'),
]

core/urls.py
from django.contrib import admin
from django.urls import path
from django.urls.conf import include
from tickets import urls as tickets_urls
from accounts import urls as accounts_urls
from pages import urls as pages_urls
from graphene_django.views import GraphQLView

urlpatterns = [
    path("graphql", GraphQLView.as_view(graphiql=True)),
    path('', include(pages_urls)),
    path('accounts/', include(accounts_urls)),
    path('tickets/', include(tickets_urls)),
    path('admin/', admin.site.urls),
]

pages/urls.py
from django.urls import path
from . import views

app_name = 'pages'
urlpatterns = [
    path('', views.landing_page, name='landing_page'),
    
]

tickets/urls.py
from django.urls import path
from . import views

app_name = 'tickets'
urlpatterns = [
    
    path('', views.index, name='index'),
    path('pull/', views.pull_request, name='pull_request'),
    path('statistics/', views.statistics_view, name='statistics'),
    path('in_progress', views.in_progress_view, name='in_progress'),
    path("help/", views.help_view, name="view_help"),
    path("privacy/", views.privacy_view, name="view_privacy"),
    path("terms/", views.terms_view, name="view_terms"),
    path('issues/', views.list_issues, name='list_issues'),
    path('changes/', views.view_changes, name='view_changes'),
    path("my/", views.my_tasks, name="my_tasks"),
    path('search/', views.search_tickets, name='search_tickets'),
    path('<int:ticket_id>/', views.ticket_detail, name='ticket_detail'),
    path('new/', views.new_ticket, name='new_ticket'),
    path('closed/', views.list_closed_tickets, name='list_closed_tickets'),
    path('hidden/', views.list_hidden_tickets, name='list_hidden_tickets'),
    path('<int:ticket_id>/edit/', views.edit_ticket, name='edit_ticket'),
    path('<int:ticket_id>/hide/', views.hide_ticket, name='hide_ticket'),
    path('<int:ticket_id>/unhide/', views.unhide_ticket, name='unhide_ticket'),
    path('<int:ticket_id>/comment/', views.new_comment, name='new_comment'),
    path('<int:ticket_id>/comment/<int:comment_id>/edit/', views.edit_comment, name='edit_comment'),
    path('<int:ticket_id>/comment/<int:comment_id>/delete/', views.delete_comment, name='delete_comment'),
    path('<int:ticket_id>/upvote/', views.upvote_ticket, name='upvote_ticket'),
    path('<int:ticket_id>/downvote/', views.downvote_ticket, name='downvote_ticket'),
    path('<int:ticket_id>/comment/<int:comment_id>/upvote/', views.upvote_comment, name='upvote_comment'),
    path('<int:ticket_id>/comment/<int:comment_id>/downvote/', views.downvote_comment, name='downvote_comment'),
    # Add api urls
    path('api/v1/list/', views.api_list_tickets, name='api_ticket_list'),
    path('api/v1/detail/<int:ticket_id>/', views.api_ticket_detail, name='api_ticket_detail'),
    path('api/v1/edit/<int:ticket_id>/', views.api_ticket_edit, name='api_ticket_edit'),
    path('api/v1/create/', views.api_ticket_create, name='api_ticket_create'),
    path('api/v1/add_comment/<int:ticket_id>/', views.api_add_comment, name='api_ticket_add_comment'),
    path('api/v1/load-users/', views.load_users, name='ajax_load_users'),
]

core/templates/anon_base.html
{% load static %}
<HTML>
<HEAD>
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/site.css' %}">
    <script src="{% static 'js/bootstrap.min.js' %}"></script>
    <TITLE>{% block title %}TTS{% endblock %}</TITLE>
</HEAD>
<BODY>
    {% include 'messages.html' %}
    <div class="container">
        <div id="header">
            <h1>TTS - Ticket Tracking System</h1>
        </div>

        <div id="content">
            {% block content %}{% endblock %}
        </div>
    </div>
</BODY>
</HTML>

core/templates/base.html
{% load static %}
<HTML>
    <HEAD>
        <link rel="stylesheet" href="{% static 'css/bootstrap/bootstrap.min.css' %}">
        <link rel="stylesheet" href="{% static 'css/site.css' %}">
        <script src="{% static 'js/bootstrap/bootstrap.bundle.min.js' %}"></script>
        <script src="{% static 'js/bootstrap/bootstrap.min.js' %}"></script>
        <script type="module" src="{% static 'js/jpost.js' %}"></script>
        <script type="module" src="{% static 'js/widgets.js' %}"></script>
        <script type="module" src="{% static 'js/global_head.js' %}"></script>
        <script type="module" src="{% static 'js/clock.js' %}"></script>
        <script type="module" src="{% static 'js/tickets.js' %}"></script>
	<link rel="icon" type="image/x-icon" href="{% static 'favicon.ico' %}">
        <TITLE>{% block title %}TTS{% endblock %}</TITLE>
        </HEAD>
    <BODY>
        {% include 'navbar.html' %}
        <!-- MAIN SECTION -->
        <main role="main" class="container">
            <div class="row">
    
                <!-- MESSAGES -->
                <div class="col-md-8 m-auto">
                    {% include 'messages.html' %}
                </div>
        
                <div class="container">
                    <div id="clock"></div>
                    
                    
                    <div id="content">
                        {% block content %}{% endblock %}
                    </div>
                </div>
            </main>
        <script src="/static/js/global_foot.js" type="module"></script>
        {% block end_js %}
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>
        <script src="https://cdn.jsdelivr.net/npm/@floating-ui/core@1.6.8"></script>
        <script src="https://cdn.jsdelivr.net/npm/@floating-ui/dom@1.6.11"></script>
        {% endblock %}
    </BODY>
</HTML>

core/templates/messages.html
{% if messages %}
    {% for message in messages %}
    <div class="alert alert-primary  alert-dismissible fade show" role="alert">
        {{ message }}
        <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    </div>
    {% endfor %}
{% endif %}

core/templates/navbar.html
<nav class="navbar navbar-expand-lg bg-body-tertiary">
  <div class="container-fluid">
    <a class="navbar-brand" href="{% url 'pages:landing_page' %}">TTS</a>
    <button
      class="navbar-toggler"
      type="button"
      data-bs-toggle="collapse"
      data-bs-target="#navbarSupportedContent"
      aria-controls="navbarSupportedContent"
      aria-expanded="false"
      aria-label="Toggle navigation"
    >
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      {% if user.is_authenticated %}
      
      {% if user.is_superuser %}
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <a href="{% url 'accounts:admin_board' %}" class="nav-link">Activity log</a>
        </li>
      </ul>
      {% endif %}
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item dropdown">
                <button class="btn btn-secondary dropdown-toggle" type="button" data-bs-toggle="dropdown" aria-expanded="false">
                    Tickets
                </button>
                <ul class="dropdown-menu">
		<li><a class="dropdown-item" href="{% url 'tickets:index' %}">All tickets</a></li>
                <li><a class="dropdown-item" href="{% url 'tickets:my_tasks' %}">My tasks</a></li>
                <li><a class="dropdown-item" href="{% url 'tickets:in_progress' %}">In Progress</a></li>
                <li><a class="dropdown-item" href="{% url 'tickets:list_issues' %}">Open issues</a> <i class="ticket_count notification-tag">0</i></li>
                <li><a class="dropdown-item" href="{% url 'tickets:list_closed_tickets' %}">Closed Tickets</a></li>
                <li><a class="dropdown-item" href="{% url 'tickets:list_hidden_tickets' %}">Hidden Tickets</a></li>
                <li><a class="dropdown-item" href="{% url 'tickets:view_changes' %}">Activity log</a></li>
                <li><a class="dropdown-item" href="{% url 'tickets:new_ticket' %}">New Ticket</a></li>
                <li><a class="dropdown-item" href="{% url 'tickets:statistics' %}">Stats</a></li>
                <li><a class="dropdown-item" href="{% url 'tickets:view_help' %}">Help</a></li>
                </ul>
        </li> 
        
      </ul>
      <form class="d-flex" method="get" action="{% url 'tickets:search_tickets' %}">
        <input
          class="form-control me-2"
          type="search"
          placeholder="Search"
          aria-label="Search"
          name="q"
        />
        <button class="btn btn-outline-success" type="submit">Search</button>
      </form>
      {% endif %}
      <ul class="navbar-nav d-flex">
        <li class="nav-item">
          {% if user.is_authenticated %}
            <a href="{% url 'accounts:profile' %}" class="nav-link d-inline">({{ user.username }})</a>
            <a href="{% url 'accounts:logout' %}" class="nav-link d-inline">Logout</a>
          {% else %}
            <a href="{% url 'accounts:login' %}" class="nav-link">Login</a>
          {% endif %}
        </li>
      </ul>
    </div>
    
  </div>
</nav>